version: '3'

services:

  ccd-adc-dev:
    container_name: ccd-adc-dev
    build: 
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/src/ccd-adc-dev